wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.1
    start_time: 1673257599.969483
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.8.1
      5: 0.13.7
      8:
      - 5
learning_rate:
  desc: null
  value: 0.0001
